---
- name: Install Docker
  hosts: docker_hosts
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root
  vars:
    som: var

  tasks:
  - name: remove docker
    yum: name=docker state=absent

  - name: remove docker-common
    yum: name=docker-common state=absent

  - name: remove docker-selinux
    yum: name=docker-selinux state=absent

  - name: remove docker-engine
    yum: name=docker-engine state=absent

  - name: install yum-utils
    yum: name=yum-utils state=latest

  - name: install device-mapper-persistent-data
    yum: name=device-mapper-persistent-data state=latest

  - name: install lvm2
    yum: name=lvm2 state=latest

  - name: Add repository
    yum_repository:
      name: docker
      description: Docker YUM repo
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo

  - name: Update the yum package index
    inline: [
        "yum makecache fast"
        ]

  - name: upgrade all packages
    yum: name='*' state=latest

  - name: install docker
    yum: name=docker-ce-17.03.0.ce-1.el7.centos.x86_64.rpm state=present

  - name: start docker
    inline: [
      , "systemctl start docker"
    ]

  - name: test docker
    inline: [
        "docker version"
    ]
